name: Deploy

on: push

jobs:
super lint: 
name: Link code base
runs-on: ubuntu-latest
steps:
   -name: Checkout code 
    uses: actions/checkout@v2
    
   -name: Run Deploy
    uses: github/super-linter@v3
    env:
    DEFAULT_BRANCH: main
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
